# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# Ejercicio 1

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/actividad5   
    steps:
        - checkout
        - run: 
              name: install dependencies
              command: |
                  sudo apt-get update    
                  sudo apt-get install python3.9-venv   
                  sudo apt-get install build-essential 
                  python3 -m venv venv
                  . venv/bin/activate
                  pip3 install -r requirements.txt
        - run:
              name: run tests  
              command: |
                  . venv/bin/activate
                  make 
                  mkdir DEPLOY-$(date +%Y-%m-%d-%H:%M:%S)
                  cp prueb* DEPLOY-$(date +%Y-%m-%d-%H:%M:%S)
                  cd DEPLOY-$(date +%Y-%m-%d-%H:%M:%S)
                  pwd
                  ls -ltr
                  ./prueba
